// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimerTalk.API.Context;

namespace TimerTalk.API.Migrations
{
    [DbContext(typeof(TimerTalkContext))]
    [Migration("20180619192136_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("TimerTalk.API.Context.Talk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Added");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Talks");
                });

            modelBuilder.Entity("TimerTalk.API.Context.TimerTick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TalkId");

                    b.Property<Guid?>("TalkId1");

                    b.Property<string>("Topic");

                    b.Property<int>("intervalSeconds");

                    b.Property<int>("secondsLeft");

                    b.HasKey("Id");

                    b.HasIndex("TalkId1");

                    b.ToTable("TimerTicks");
                });

            modelBuilder.Entity("TimerTalk.API.Context.TimerTick", b =>
                {
                    b.HasOne("TimerTalk.API.Context.Talk", "Talk")
                        .WithMany("TimerTicks")
                        .HasForeignKey("TalkId1");
                });
#pragma warning restore 612, 618
        }
    }
}
