// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimerTalk.API.Context;

namespace TimerTalk.API.Migrations
{
    [DbContext(typeof(TimerTalkContext))]
    [Migration("20180626134301_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("TimerTalk.API.Models.Talk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Added");

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Talks");
                });

            modelBuilder.Entity("TimerTalk.API.Models.TimerTick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Index");

                    b.Property<int>("IntervalSeconds");

                    b.Property<int>("SecondsLeft");

                    b.Property<int>("TalkId");

                    b.Property<string>("Topic");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TalkId");

                    b.ToTable("TimerTicks");
                });

            modelBuilder.Entity("TimerTalk.API.Models.TimerTick", b =>
                {
                    b.HasOne("TimerTalk.API.Models.Talk", "Talk")
                        .WithMany("TimerTicks")
                        .HasForeignKey("TalkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
